### ISSUE TITLE
all the links are wrong

### ISSUE THREAD

**Issue by MNLKuzmin** [learn-co-curriculum/dsc-spark-dataframes#1]
## Link to Canvas

https://learning.flatironschool.com/courses/5318/assignments/189794?module_item_id=422634

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ X] Other (explain below)

### Source

```

Now that we have a SparkSession, we can create a DataFrame using the createDataFrame method ([documentation here](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.SparkSession.createDataFrame.html))! One way to do this would just be to hard-code the data using built-in Python types:


Now, to perform calculations to find the mean of a column (without aggregating first), we'll have to import functions from pyspark.sql. As always, to read more about them, check out the [documentation](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html#module-pyspark.sql.functions).
```

### Concern

all of the links to documentation to pyspark sql are wrong. they all give 404 errors
not all these two that I copied, all of them

## What OS Are You Using?

- [ X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
thanks for opening this issue :wave:. I have updated all the relevant links with the new url to the documentation and they open correctly at this time. Fixed with [2e2113e](https://github.com/learn-co-curriculum/dsc-spark-dataframes/commit/2e2113e7a6ea1e2db1bc5113fca2ab3af179eaec)
